### ISSUE TITLE
still parsing- has been 35 minutes.

### ISSUE THREAD

**Issue by evewurtele** [urmi-21/MOG-debugging#10]
![screen shot 2018-04-23 at 10 21 47 am](https://user-images.githubusercontent.com/20331871/39136153-316a0300-46e0-11e8-9419-3c3d7ab5aa63.png)
finally froz after 45 min.   redownloading MOG from drive, just in case.... The April  23 version   , (no chance you mislabeled?)

**Comment by urmi-21** [comment]
implemented much faster conversion algorithm
