### ISSUE TITLE
doesnt ID number of columns with study metadata correctly

### ISSUE THREAD

**Issue by evewurtele** [urmi-21/MOG-debugging#9]
![screen shot 2018-04-23 at 9 47 58 am](https://user-images.githubusercontent.com/20331871/39134136-879a8f92-46db-11e8-9ad1-704fa734639f.png)

 (using maize study metadata .cvs file)

**Comment by urmi-21** [comment]
This issue was moved to urmi-21/MetaOmGraph#9
